name: deploy vps
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      #xai docker di
      - uses: actions/checkout@v4
      - name: Create .env file
        run: echo "${{secrets.ENV_PROD}}" > .env
      - name: Build docker images
        run: docker build --platform linux/amd64 -t hoangday185/graphql-nest:v0 .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker images
        run: docker push hoangday185/graphql-nest:v0
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Excuting remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            docker login -u "${{secrets.DOCKERHUB_USERNAME}}" -p "${{secrets.DOCKERHUB_PASSWORD}}"
            docker pull hoangday185/graphql-nest:v0
            docker rm -f dev_nest_graphql
            docker container run -dp 6969:3000 --name dev_nest_graphql hoangday185/graphql-nest:v0
            docker network connect graphql_network dev_nest_graphql
            docker restart dev_nest_graphql
            docker image prune -f
